# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5ab527b816924848187c06cf4b330cdd7426ecb0c98c9a8a3dd389f2a728e329e7be6c89d3e2e3e7dfbb0e85a52fe8c1a4f9fd33560569d62dc550513d8521

test:
  secret_key_base: 3770d3e9ad82ad8f84478eed7fb31685bf4c0acade38d36e446423f15233cf2c22f28c08ae4e4dd87be919a85404a39ca7bd56a9cec8cc62cabf5958dd9d4888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
